# .github/workflows/docker-publish.yml
name: "Docker — Front & Back"

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish_front:
    name: "Docker — Front"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: "docker-front-${{ github.sha }}"
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Capture creation timestamp
        id: created
        run: |
          ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          {
            echo "created=$ts"
            echo "date=$ts"
          } >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/nejrima/projet10
          flavor: |
            prefix=front-
            latest=false
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=dev,enable=${{ github.ref_name == 'dev' }}
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: front
          file: front/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.created.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
      - name: Publish summary
        run: |
          {
            echo "### Docker Image Published";
            echo "- Image: docker.io/nejrima/projet10";
            echo "- Tags:";
            printf '%s\n' "${{ steps.meta.outputs.tags }}" | while read -r tag; do
              [ -n "$tag" ] && echo "  - $tag";
            done;
          } >> "$GITHUB_STEP_SUMMARY"

  publish_back:
    name: "Docker — Back"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: "docker-back-${{ github.sha }}"
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Capture creation timestamp
        id: created
        run: |
          ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          {
            echo "created=$ts"
            echo "date=$ts"
          } >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/nejrima/projet10
          flavor: |
            prefix=back-
            latest=false
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=dev,enable=${{ github.ref_name == 'dev' }}
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: back
          file: back/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.created.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
      - name: Publish summary
        run: |
          {
            echo "### Docker Image Published";
            echo "- Image: docker.io/nejrima/projet10";
            echo "- Tags:";
            printf '%s\n' "${{ steps.meta.outputs.tags }}" | while read -r tag; do
              [ -n "$tag" ] && echo "  - $tag";
            done;
          } >> "$GITHUB_STEP_SUMMARY"
